/**
 * ProgressFooter 컴포넌트
 * Generated by v0.dev, adapted for project structure
 * Boris Cherny 원칙: 1-B에서 정의한 타입을 import하여 사용
 */

"use client";

import type { ProgressFooterProps, SectionId } from "@/types";

export function ProgressFooter({ progress, onPrev, onNext }: ProgressFooterProps) {
  const { currentSection, totalSections } = progress;
  const isPrevDisabled = currentSection === 1;
  const isNextDisabled = currentSection === totalSections;

  return (
    <footer className="fixed bottom-0 left-0 right-0 z-50 h-20 border-t border-gray-200 bg-white">
      <div className="mx-auto flex h-full max-w-content items-center justify-between px-6">
        {/* 이전 버튼 */}
        <button
          onClick={onPrev}
          disabled={isPrevDisabled}
          className="rounded-lg border border-gray-300 px-6 py-2.5 font-medium text-gray-700 transition-all hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-40"
        >
          이전
        </button>

        {/* 진행 상태 Dots (17개) */}
        <div className="flex items-center gap-2">
          {Array.from({ length: totalSections }, (_, i) => {
            const sectionNum = (i + 1) as SectionId;
            const isActive = sectionNum === currentSection;

            return (
              <div
                key={sectionNum}
                className={`rounded-full transition-all ${
                  isActive ? "h-3 w-3 bg-primary" : "h-2 w-2 bg-gray-300"
                }`}
                aria-label={`섹션 ${sectionNum} / ${totalSections}`}
                aria-current={isActive ? "step" : undefined}
              />
            );
          })}
        </div>

        {/* 다음 버튼 */}
        <button
          onClick={onNext}
          disabled={isNextDisabled}
          className="rounded-lg bg-primary px-6 py-2.5 font-medium text-white transition-all hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-40"
        >
          다음
        </button>
      </div>
    </footer>
  );
}
