/**
 * TopbarHeader 컴포넌트
 * Generated by v0.dev, adapted for project structure
 * Boris Cherny 원칙: 1-B에서 정의한 타입을 import하여 사용
 */

import type { TopbarHeaderProps } from "@/types";

export function TopbarHeader({ title, progress }: TopbarHeaderProps) {
  return (
    <header 
      className="fixed top-0 z-50 w-full h-16" 
      style={{ backgroundColor: "#004B8D" }}
    >
      <div className="mx-auto flex h-full max-w-content items-center justify-between px-6">
        <h1 className="text-lg font-semibold text-white">{title}</h1>
        <div className="text-white">
          <span className="font-medium">
            {progress.currentSection} / {progress.totalSections}
          </span>
        </div>
      </div>
    </header>
  );
}
